import pandas as pd

# Load CSV
df = pd.read_csv("data/enrollment.csv")

# mapping (old_name -> new_name)
district_map = {
    # --- UTTAR PRADESH ---
    "Agra": "Agra", "Aligarh": "Aligarh", "Allahabad": "Prayagraj", "Ambedkar Nagar": "Ambedkar Nagar", 
    "Amethi": "Amethi", "Amroha": "Amroha", "Auraiya": "Auraiya", "Ayodhya": "Ayodhya", 
    "Azamgarh": "Azamgarh", "Baghpat": "Baghpat", "Bahraich": "Bahraich", "Ballia": "Ballia", 
    "Balrampur": "Balrampur", "Banda": "Banda", "Barabanki": "Barabanki", "Bareilly": "Bareilly", 
    "Basti": "Basti", "Bhadohi": "Bhadohi", "Bijnor": "Bijnor", "Budaun": "Budaun", 
    "Bulandshahr": "Bulandshahr", "Chandauli": "Chandauli", "Chitrakoot": "Chitrakoot", 
    "Deoria": "Deoria", "Etah": "Etah", "Etawah": "Etawah", "Faizabad": "Ayodhya", 
    "Farrukhabad": "Farrukhabad", "Fatehpur": "Fatehpur", "Firozabad": "Firozabad", 
    "Gautam Buddha Nagar": "Gautam Buddha Nagar", "Ghaziabad": "Ghaziabad", "Ghazipur": "Ghazipur", 
    "Gonda": "Gonda", "Gorakhpur": "Gorakhpur", "Hamirpur": "Hamirpur", "Hapur": "Hapur", 
    "Hardoi": "Hardoi", "Hathras": "Hathras", "Jalaun": "Jalaun", "Jaunpur": "Jaunpur", 
    "Jhansi": "Jhansi", "Kannauj": "Kannauj", "Kanpur Dehat": "Kanpur Dehat", 
    "Kanpur Nagar": "Kanpur Nagar", "Kasganj": "Kasganj", "Kaushambi": "Kaushambi", 
    "Kheri": "Lakhimpur Kheri", "Kushinagar": "Kushinagar", "Lalitpur": "Lalitpur", 
    "Lucknow": "Lucknow", "Maharajganj": "Maharajganj", "Mahoba": "Mahoba", "Mainpuri": "Mainpuri", 
    "Mathura": "Mathura", "Mau": "Mau", "Meerut": "Meerut", "Mirzapur": "Mirzapur", 
    "Moradabad": "Moradabad", "Muzaffarnagar": "Muzaffarnagar", "Pilibhit": "Pilibhit", 
    "Pratapgarh": "Pratapgarh", "Prayagraj": "Prayagraj", "Rae Bareli": "Rae Bareli", 
    "Rampur": "Rampur", "Saharanpur": "Saharanpur", "Sambhal": "Sambhal", "Sant Kabir Nagar": "Sant Kabir Nagar", 
    "Shahjahanpur": "Shahjahanpur", "Shamli": "Shamli", "Shravasti": "Shravasti", 
    "Siddharthnagar": "Siddharthnagar", "Sitapur": "Sitapur", "Sonbhadra": "Sonbhadra", 
    "Sultanpur": "Sultanpur", "Unnao": "Unnao", "Varanasi": "Varanasi",

    # --- MADHYA PRADESH ---
    "Agar Malwa": "Agar Malwa", "Alirajpur": "Alirajpur", "Anuppur": "Anuppur", "Ashok Nagar": "Ashoknagar", 
    "Ashoknagar": "Ashoknagar", "Balaghat": "Balaghat", "Barwani": "Barwani", "Betul": "Betul", 
    "Bhind": "Bhind", "Bhopal": "Bhopal", "Burhanpur": "Burhanpur", "Chhatarpur": "Chhatarpur", 
    "Chhindwara": "Chhindwara", "Damoh": "Damoh", "Datia": "Datia", "Dewas": "Dewas", 
    "Dhar": "Dhar", "Dindori": "Dindori", "East Nimar": "Khandwa", "Guna": "Guna", 
    "Gwalior": "Gwalior", "Harda": "Harda", "Harda *": "Harda", "Hoshangabad": "Narmadapuram", 
    "Indore": "Indore", "Jabalpur": "Jabalpur", "Jhabua": "Jhabua", "Katni": "Katni", 
    "Khandwa": "Khandwa", "Khargone": "Khargone", "Mandla": "Mandla", "Mandsaur": "Mandsaur", 
    "Morena": "Morena", "Narmadapuram": "Narmadapuram", "Narsimhapur": "Narsinghpur", 
    "Narsinghpur": "Narsinghpur", "Neemuch": "Neemuch", "Niwari": "Niwari", "Panna": "Panna", 
    "Raisen": "Raisen", "Rajgarh": "Rajgarh", "Ratlam": "Ratlam", "Rewa": "Rewa", 
    "Sagar": "Sagar", "Satna": "Satna", "Sehore": "Sehore", "Seoni": "Seoni", 
    "Shahdol": "Shahdol", "Shajapur": "Shajapur", "Sheopur": "Sheopur", "Shivpuri": "Shivpuri", 
    "Sidhi": "Sidhi", "Singrauli": "Singrauli", "Tikamgarh": "Tikamgarh", "Ujjain": "Ujjain", 
    "Umaria": "Umaria", "Vidisha": "Vidisha", "West Nimar": "Khargone",

    # --- KARNATAKA ---
    "Bagalkot": "Bagalkot", "Bagalkot *": "Bagalkot", "Ballari": "Ballari", "Bangalore": "Bengaluru Urban", 
    "Bangalore Rural": "Bengaluru Rural", "Belgaum": "Belagavi", "Bellary": "Ballari", 
    "Belagavi": "Belagavi", "Bengaluru Rural": "Bengaluru Rural", "Bengaluru Urban": "Bengaluru Urban", 
    "Bidar": "Bidar", "Bijapur": "Vijayapura", "Bijapur(Kar)": "Vijayapura", "Chamarajanagar": "Chamarajanagar", 
    "Chamarajanagar *": "Chamarajanagar", "Chamrajanagar": "Chamarajanagar", "Chamrajnagar": "Chamarajanagar", 
    "Chikkaballapur": "Chikkaballapur", "Chikkamagaluru": "Chikkamagaluru", "Chickmagalur": "Chikkamagaluru", 
    "Chikmagalur": "Chikkamagaluru", "Chitradurga": "Chitradurga", "Dakshina Kannada": "Dakshina Kannada", 
    "Davanagere": "Davanagere", "Davangere": "Davanagere", "Dharwad": "Dharwad", "Gadag": "Gadag", 
    "Gadag *": "Gadag", "Hassan": "Hassan", "Hasan": "Hassan", "Haveri": "Haveri", "Haveri *": "Haveri", 
    "Kalaburagi": "Kalaburagi", "Gulbarga": "Kalaburagi", "Kodagu": "Kodagu", "Kolar": "Kolar", 
    "Koppal": "Koppal", "Mandya": "Mandya", "Mysuru": "Mysuru", "Mysore": "Mysuru", 
    "Raichur": "Raichur", "Ramanagara": "Ramanagara", "Ramanagar": "Ramanagara", "Shivamogga": "Shivamogga", 
    "Shimoga": "Shivamogga", "Tumakuru": "Tumakuru", "Tumkur": "Tumakuru", "Udupi": "Udupi", 
    "Udupi *": "Udupi", "Uttara Kannada": "Uttara Kannada", "Vijayapura": "Vijayapura", 
    "Yadgir": "Yadgir", "Vijayanagara": "Vijayanagara",

    # --- WEST BENGAL ---
    "Alipurduar": "Alipurduar", "Bankura": "Bankura", "Birbhum": "Birbhum", "Cooch Behar": "Cooch Behar", 
    "Coochbehar": "Cooch Behar", "Dakshin Dinajpur": "Dakshin Dinajpur", "Darjeeling": "Darjeeling", 
    "Darjiling": "Darjeeling", "Hooghly": "Hooghly", "Hooghiy": "Hooghly", "Hugli": "Hooghly", 
    "Howrah": "Howrah", "Haora": "Howrah", "Hawrah": "Howrah", "Jalpaiguri": "Jalpaiguri", 
    "Jhargram": "Jhargram", "Kalimpong": "Kalimpong", "Kolkata": "Kolkata", "Malda": "Malda", 
    "Maldah": "Malda", "Murshidabad": "Murshidabad", "Nadia": "Nadia", "North 24 Parganas": "North 24 Parganas", 
    "North Twenty Four Parganas": "North 24 Parganas", "Paschim Bardhaman": "Paschim Bardhaman", 
    "Paschim Medinipur": "Paschim Medinipur", "Purba Bardhaman": "Purba Bardhaman", "Burdwan": "Purba Bardhaman", 
    "Purba Medinipur": "Purba Medinipur", "Purulia": "Purulia", "Puruliya": "Purulia", 
    "South 24 Parganas": "South 24 Parganas", "South Twenty Four Parganas": "South 24 Parganas", 
    "Uttar Dinajpur": "Uttar Dinajpur", "24 Paraganas North": "North 24 Parganas", 
    "24 Paraganas South": "South 24 Parganas",

    # --- MAHARASHTRA ---
    "Ahilyanagar": "Ahilyanagar", "Ahmednagar": "Ahilyanagar", "Akola": "Akola", "Amravati": "Amravati", 
    "Beed": "Beed", "Bid": "Beed", "Bhandara": "Bhandara", "Buldhana": "Buldhana", "Buldana": "Buldhana", 
    "Chandrapur": "Chandrapur", "Chhatrapati Sambhajinagar": "Chhatrapati Sambhajinagar", "Aurangabad": "Chhatrapati Sambhajinagar", 
    "Dharashiv": "Dharashiv", "Osmanabad": "Dharashiv", "Dhule": "Dhule", "Gadchiroli": "Gadchiroli", 
    "Gondia": "Gondia", "Gondiya": "Gondia", "Gondiya *": "Gondia", "Hingoli": "Hingoli", 
    "Hingoli *": "Hingoli", "Jalgaon": "Jalgaon", "Jalna": "Jalna", "Kolhapur": "Kolhapur", 
    "Latur": "Latur", "Mumbai City": "Mumbai City", "Mumbai Suburban": "Mumbai Suburban", 
    "Nagpur": "Nagpur", "Nanded": "Nanded", "Nandurbar": "Nandurbar", "Nandurbar *": "Nandurbar", 
    "Nashik": "Nashik", "Palghar": "Palghar", "Parbhani": "Parbhani", "Pune": "Pune", 
    "Raigad": "Raigad", "Raigarh": "Raigad", "Ratnagiri": "Ratnagiri", "Sangli": "Sangli", 
    "Satara": "Satara", "Sindhudurg": "Sindhudurg", "Solapur": "Solapur", "Thane": "Thane", 
    "Dist : Thane": "Thane", "Wardha": "Wardha", "Washim": "Washim", "Washim *": "Washim", "Yavatmal": "Yavatmal",

    # --- RAJASTHAN ---
    "Ajmer": "Ajmer", "Alwar": "Alwar", "Anoopgarh": "REMOVED/MERGED", "Anupgarh": "REMOVED/MERGED",
    "Balotra": "Balotra", "Banswara": "Banswara", "Baran": "Baran", "Barmer": "Barmer",
    "Beawar": "Beawar", "Bharatpur": "Bharatpur", "Bhilwara": "Bhilwara", "Bikaner": "Bikaner",
    "Bundi": "Bundi", "Chittaurgarh": "Chittorgarh", "Chittorgarh": "Chittorgarh", "Churu": "Churu",
    "Dausa": "Dausa", "Deeg": "Deeg", "Dhaulpur": "Dholpur", "Dholpur": "Dholpur",
    "Didwana-Kuchaman": "Didwana-Kuchaman", "Dudu": "REMOVED/MERGED", "Dungarpur": "Dungarpur",
    "Ganganagar": "Ganganagar", "Gangapur City": "REMOVED/MERGED", "Hanumangarh": "Hanumangarh",
    "Jaipur": "Jaipur", "Jaipur Rural": "REMOVED/MERGED", "Jaisalmer": "Jaisalmer",
    "Jalor": "Jalore", "Jalore": "Jalore", "Jhalawar": "Jhalawar", "Jhunjhunu": "Jhunjhunu",
    "Jhunjhunun": "Jhunjhunu", "Jodhpur": "Jodhpur", "Jodhpur Rural": "REMOVED/MERGED",
    "Karauli": "Karauli", "Kekri": "REMOVED/MERGED", "Khairthal-Tijara": "Khairthal-Tijara",
    "Kota": "Kota", "Kotputli-Behror": "Kotputli-Behror", "Nagaur": "Nagaur",
    "Neem Ka Thana": "REMOVED/MERGED", "Pali": "Pali", "Phalodi": "Phalodi",
    "Pratapgarh": "Pratapgarh", "Rajsamand": "Rajsamand", "Salumbar": "Salumbar",
    "Sanchore": "REMOVED/MERGED", "Sawai Madhopur": "Sawai Madhopur",
    "Shahpura": "REMOVED/MERGED", "Sikar": "Sikar", "Sirohi": "Sirohi",
    "Tonk": "Tonk", "Udaipur": "Udaipur",

    # --- TELANGANA ---
    "Adilabad": "Adilabad", "Bhadradri Kothagudem": "Bhadradri Kothagudem", "Hanumakonda": "Hanumakonda",
    "Hyderabad": "Hyderabad", "Jagtial": "Jagtial", "Jagitial": "Jagtial", "Jangaon": "Jangaon",
    "Jangoan": "Jangaon", "Jayashankar Bhupalpally": "Jayashankar Bhupalpally",
    "Jogulamba Gadwal": "Jogulamba Gadwal", "Rangareddy": "Rangareddy", "K.V. Rangareddy": "Rangareddy",
    "Kamareddy": "Kamareddy", "Karimnagar": "Karimnagar", "Khammam": "Khammam",
    "Kumuram Bheem Asifabad": "Kumuram Bheem Asifabad", "Komaram Bheem": "Kumuram Bheem Asifabad",
    "Mahabubabad": "Mahabubabad", "Mahabubnagar": "Mahabubnagar", "Mancherial": "Mancherial",
    "Medak": "Medak", "Medchal-Malkajgiri": "Medchal-Malkajgiri", "Medchal Malkajgiri": "Medchal-Malkajgiri",
    "Medchal?Malkajgiri": "Medchal-Malkajgiri", "MedchalÃ¢ÂˆÂ’Malkajgiri": "Medchal-Malkajgiri",
    "Mulugu": "Mulugu", "Nagarkurnool": "Nagarkurnool", "Nalgonda": "Nalgonda",
    "Narayanpet": "Narayanpet", "Nirmal": "Nirmal", "Nizamabad": "Nizamabad",
    "Peddapalli": "Peddapalli", "Rajanna Sircilla": "Rajanna Sircilla", "Sangareddy": "Sangareddy",
    "Siddipet": "Siddipet", "Suryapet": "Suryapet", "Vikarabad": "Vikarabad",
    "Wanaparthy": "Wanaparthy", "Warangal": "Warangal", "Warangal (Urban)": "Hanumakonda",
    "Warangal Urban": "Hanumakonda", "Warangal Rural": "Warangal",
    "Yadadri Bhuvanagiri": "Yadadri Bhuvanagiri", "Yadadri.": "Yadadri Bhuvanagiri",

    # --- GUJARAT ---
    "Ahmedabad": "Ahmedabad", "Ahmadabad": "Ahmedabad", "Amreli": "Amreli", "Anand": "Anand",
    "Arvalli": "Aravalli", "Aravalli": "Aravalli", "Banaskantha": "Banaskantha",
    "Banas Kantha": "Banaskantha", "Bharuch": "Bharuch", "Bhavnagar": "Bhavnagar",
    "Botad": "Botad", "Chhota Udepur": "Chhota Udepur", "Chhotaudepur": "Chhota Udepur",
    "Dahod": "Dahod", "Dohad": "Dahod", "Dang": "Dang", "The Dangs": "Dang",
    "Devbhumi Dwarka": "Devbhumi Dwarka", "Devbhoomi Dwarka": "Devbhumi Dwarka",
    "Gandhinagar": "Gandhinagar", "Gir Somnath": "Gir Somnath", "Jamnagar": "Jamnagar",
    "Junagadh": "Junagadh", "Kachchh": "Kutch", "Kutch": "Kutch", "Kheda": "Kheda",
    "Mehsana": "Mehsana", "Mahesana": "Mehsana", "Mahisagar": "Mahisagar", "Morbi": "Morbi",
    "Narmada": "Narmada", "Navsari": "Navsari", "Panchmahal": "Panchmahal",
    "Panch Mahals": "Panchmahal", "Panchmahals": "Panchmahal", "Patan": "Patan",
    "Porbandar": "Porbandar", "Rajkot": "Rajkot", "Sabarkantha": "Sabarkantha",
    "Sabar Kantha": "Sabarkantha", "Surat": "Surat", "Surendranagar": "Surendranagar",
    "Surendra Nagar": "Surendranagar", "Tapi": "Tapi", "Vadodara": "Vadodara", "Valsad": "Valsad",

    # --- ASSAM ---
    "Bajali": "Bajali", "Baksa": "Baksa", "Barpeta": "Barpeta", "Biswanath": "Biswanath",
    "Bongaigaon": "Bongaigaon", "Cachar": "Cachar", "Charaideo": "Charaideo", "Chirang": "Chirang",
    "Darrang": "Darrang", "Dhemaji": "Dhemaji", "Dhubri": "Dhubri", "Dibrugarh": "Dibrugarh",
    "Dima Hasao": "Dima Hasao", "North Cachar Hills": "Dima Hasao", "Goalpara": "Goalpara",
    "Golaghat": "Golaghat", "Hailakandi": "Hailakandi", "Hojai": "Hojai", "Jorhat": "Jorhat",
    "Kamrup": "Kamrup", "Kamrup Metropolitan": "Kamrup Metropolitan", "Kamrup Metro": "Kamrup Metropolitan",
    "Karbi Anglong": "Karbi Anglong", "Sribhumi": "Sribhumi", "Karimganj": "Sribhumi",
    "Kokrajhar": "Kokrajhar", "Lakhimpur": "Lakhimpur", "Majuli": "Majuli", "Morigaon": "Morigaon",
    "Marigaon": "Morigaon", "Nagaon": "Nagaon", "Nalbari": "Nalbari", "Sivasagar": "Sivasagar",
    "Sibsagar": "Sivasagar", "Sonitpur": "Sonitpur", "South Salmara-Mankachar": "South Salmara-Mankachar",
    "South Salmara Mankachar": "South Salmara-Mankachar", "Tamulpur": "Tamulpur",
    "Tamulpur District": "Tamulpur", "Tinsukia": "Tinsukia", "Udalguri": "Udalguri",
    "West Karbi Anglong": "West Karbi Anglong",

    # --- JHARKHAND ---
    "Bokaro": "Bokaro", "Bokaro *": "Bokaro", "Chatra": "Chatra", "Deoghar": "Deoghar",
    "Dhanbad": "Dhanbad", "Dumka": "Dumka", "East Singhbhum": "East Singhbhum",
    "East Singhbum": "East Singhbhum", "Purbi Singhbhum": "East Singhbhum", "Garhwa": "Garhwa",
    "Garhwa *": "Garhwa", "Giridih": "Giridih", "Godda": "Godda", "Gumla": "Gumla",
    "Hazaribagh": "Hazaribagh", "Hazaribag": "Hazaribagh", "Jamtara": "Jamtara",
    "Khunti": "Khunti", "Koderma": "Koderma", "Kodarma": "Koderma", "Latehar": "Latehar",
    "Lohardaga": "Lohardaga", "Pakur": "Pakur", "Pakaur": "Pakur", "Palamu": "Palamu",
    "Palamau": "Palamu", "Ramgarh": "Ramgarh", "Ranchi": "Ranchi", "Sahibganj": "Sahibganj",
    "Sahebganj": "Sahibganj", "Seraikela-Kharsawan": "Seraikela-Kharsawan", "Simdega": "Simdega",
    "West Singhbhum": "West Singhbhum", "Pashchimi Singhbhum": "West Singhbhum",

    # --- JAMMU & KASHMIR & LADAKH ---
    "Anantnag": "Anantnag", "Bandipora": "Bandipora", "Bandipore": "Bandipora",
    "Bandipur": "Bandipora", "Baramulla": "Baramulla", "Baramula": "Baramulla",
    "Budgam": "Budgam", "Badgam": "Budgam", "Doda": "Doda", "Ganderbal": "Ganderbal",
    "Jammu": "Jammu", "Kathua": "Kathua", "Kishtwar": "Kishtwar", "Kulgam": "Kulgam",
    "Kupwara": "Kupwara", "Poonch": "Poonch", "Punch": "Poonch", "Pulwama": "Pulwama",
    "Rajouri": "Rajouri", "Rajauri": "Rajouri", "Ramban": "Ramban", "Reasi": "Reasi",
    "Samba": "Samba", "Shopian": "Shopian", "Shupiyan": "Shopian", "Srinagar": "Srinagar",
    "Udhampur": "Udhampur", "Kargil": "Kargil", "Leh": "Leh", "Leh (Ladakh)": "Leh",
    "Leh Ladakh": "Leh", "Ladakh": "Leh", "?": "REMOVED/CLEANUP",

    # --- PUNJAB & HARYANA ---
    "Amritsar": "Amritsar", "Barnala": "Barnala", "Bathinda": "Bathinda", "Faridkot": "Faridkot",
    "Fatehgarh Sahib": "Fatehgarh Sahib", "Fazilka": "Fazilka", "Ferozepur": "Ferozepur",
    "Firozpur": "Ferozepur", "Gurdaspur": "Gurdaspur", "Hoshiarpur": "Hoshiarpur",
    "Jalandhar": "Jalandhar", "Kapurthala": "Kapurthala", "Ludhiana": "Ludhiana",
    "Malerkotla": "Malerkotla", "Mansa": "Mansa", "Moga": "Moga", "Sri Muktsar Sahib": "Sri Muktsar Sahib",
    "Muktsar": "Sri Muktsar Sahib", "Shaheed Bhagat Singh Nagar": "Shaheed Bhagat Singh Nagar",
    "Nawanshahr": "Shaheed Bhagat Singh Nagar", "Pathankot": "Pathankot", "Patiala": "Patiala",
    "Rupnagar": "Rupnagar", "Ropar": "Rupnagar", "S.A.S. Nagar": "S.A.S. Nagar", "S.A.S Nagar": "S.A.S. Nagar",
    "S.A.S Nagar(Mohali)": "S.A.S. Nagar", "Sas Nagar (Mohali)": "S.A.S. Nagar", "Mohali": "S.A.S. Nagar",
    "Sangrur": "Sangrur", "Tarn Taran": "Tarn Taran", "Ambala": "Ambala", "Bhiwani": "Bhiwani",
    "Charkhi Dadri": "Charkhi Dadri", "Faridabad": "Faridabad", "Fatehabad": "Fatehabad",
    "Gurugram": "Gurugram", "Gurgaon": "Gurugram", "Hisar": "Hisar", "Jhajjar": "Jhajjar",
    "Jhajjar *": "Jhajjar", "Jind": "Jind", "Kaithal": "Kaithal", "Karnal": "Karnal",
    "Kurukshetra": "Kurukshetra", "Mahendragarh": "Mahendragarh", "Nuh": "Nuh",
    "Mewat": "Nuh", "Palwal": "Palwal", "Panchkula": "Panchkula", "Panipat": "Panipat",
    "Rewari": "Rewari", "Rohtak": "Rohtak", "Sirsa": "Sirsa", "Sonipat": "Sonipat",
    "Yamunanagar": "Yamunanagar", "Yamuna Nagar": "Yamunanagar",

    # --- ARUNACHAL PRADESH & NAGALAND ---
    "Anjaw": "Anjaw", "Changlang": "Changlang", "Dibang Valley": "Dibang Valley",
    "East Kameng": "East Kameng", "East Siang": "East Siang", "Kamle": "Kamle",
    "Kra Daadi": "Kra Daadi", "Kurung Kumey": "Kurung Kumey", "Leparada": "Leparada",
    "Lohit": "Lohit", "Longding": "Longding", "Lower Dibang Valley": "Lower Dibang Valley",
    "Lower Siang": "Lower Siang", "Lower Subansiri": "Lower Subansiri", "Namsai": "Namsai",
    "Pakke-Kessang": "Pakke-Kessang", "Pakke Kessang": "Pakke-Kessang", "Papum Pare": "Papum Pare",
    "Shi-Yomi": "Shi-Yomi", "Shi Yomi": "Shi-Yomi", "Siang": "Siang", "Tawang": "Tawang",
    "Tirap": "Tirap", "Upper Siang": "Upper Siang", "Upper Subansiri": "Upper Subansiri",
    "West Kameng": "West Kameng", "West Siang": "West Siang", "Chumoukedima": "Chumoukedima",
    "Chumukedima": "Chumoukedima", "Dimapur": "Dimapur", "Kiphire": "Kiphire",
    "Kohima": "Kohima", "Longleng": "Longleng", "Meluri": "Meluri", "Mokokchung": "Mokokchung",
    "Mon": "Mon", "Niuland": "Niuland", "Noklak": "Noklak", "Peren": "Peren", "Phek": "Phek",
    "Shamator": "Shamator", "Tseminyu": "Tseminyu", "Tuensang": "Tuensang", "Wokha": "Wokha",
    "Zunheboto": "Zunheboto",

    # --- UTTARAKHAND & KERALA ---
    "Almora": "Almora", "Bageshwar": "Bageshwar", "Chamoli": "Chamoli", "Champawat": "Champawat",
    "Dehradun": "Dehradun", "Haridwar": "Haridwar", "Hardwar": "Haridwar", "Nainital": "Nainital",
    "Pauri Garhwal": "Pauri Garhwal", "Garhwal": "Pauri Garhwal", "Pithoragarh": "Pithoragarh",
    "Rudraprayag": "Rudraprayag", "Tehri Garhwal": "Tehri Garhwal", "Udham Singh Nagar": "Udham Singh Nagar",
    "Udham Singh Nagar *": "Udham Singh Nagar", "Uttarkashi": "Uttarkashi", "Alappuzha": "Alappuzha",
    "Alleppey": "Alappuzha", "Ernakulam": "Ernakulam", "Idukki": "Idukki", "Kannur": "Kannur",
    "Cannanore": "Kannur", "Kasaragod": "Kasaragod", "Kasargod": "Kasaragod", "Kollam": "Kollam",
    "Quilon": "Kollam", "Kottayam": "Kottayam", "Kozhikode": "Kozhikode", "Calicut": "Kozhikode",
    "Malappuram": "Malappuram", "Palakkad": "Palakkad", "Palghat": "Palakkad",
    "Pathanamthitta": "Pathanamthitta", "Thiruvananthapuram": "Thiruvananthapuram",
    "Trivandrum": "Thiruvananthapuram", "Thrissur": "Thrissur", "Trichur": "Thrissur", "Wayanad": "Wayanad",

    # --- DELHI & HIMACHAL PRADESH ---
    "Central Delhi": "Central Delhi", "East Delhi": "East Delhi", "Najafgarh": "Najafgarh",
    "New Delhi": "New Delhi", "North Delhi": "North Delhi", "North East": "North East Delhi",
    "North East    *": "North East Delhi", "North East Delhi": "North East Delhi",
    "North West Delhi": "North West Delhi", "South Delhi": "South Delhi",
    "South East Delhi": "South East Delhi", "South West Delhi": "South West Delhi",
    "West Delhi": "West Delhi", "Shahdara": "REMOVED/MERGED", "Old Delhi": "Old Delhi",
    "Bilaspur": "Bilaspur", "Chamba": "Chamba", "Hamirpur": "Hamirpur", "Kangra": "Kangra",
    "Kinnaur": "Kinnaur", "Kullu": "Kullu", "Lahaul and Spiti": "Lahaul and Spiti",
    "Lahaul And Spiti": "Lahaul and Spiti", "Lahul & Spiti": "Lahaul and Spiti",
    "Lahul And Spiti": "Lahaul and Spiti", "Mandi": "Mandi", "Shimla": "Shimla",
    "Sirmaur": "Sirmaur", "Sirmour": "Sirmaur", "Solan": "Solan", "Una": "Una",

    # --- NE STATES (MEGHALAYA, MANIPUR, MIZORAM, SIKKIM) ---
    "East Garo Hills": "East Garo Hills", "East Jaintia Hills": "East Jaintia Hills",
    "East Khasi Hills": "East Khasi Hills", "Eastern West Khasi Hills": "Eastern West Khasi Hills",
    "North Garo Hills": "North Garo Hills", "Ri Bhoi": "Ri Bhoi", "South Garo Hills": "South Garo Hills",
    "South West Garo Hills": "South West Garo Hills", "South West Khasi Hills": "South West Khasi Hills",
    "West Garo Hills": "West Garo Hills", "West Jaintia Hills": "West Jaintia Hills",
    "West Khasi Hills": "West Khasi Hills", "Jaintia Hills": "West Jaintia Hills",
    "Bishnupur": "Bishnupur", "Chandel": "Chandel", "Churachandpur": "Churachandpur",
    "Imphal East": "Imphal East", "Imphal West": "Imphal West", "Jiribam": "Jiribam",
    "Kakching": "Kakching", "Kangpokpi": "Kangpokpi", "Sadar Hills": "Kangpokpi",
    "Pherzawl": "Pherzawl", "Senapati": "Senapati", "Tamenglong": "Tamenglong", "Thoubal": "Thoubal",
    "Ukhrul": "Ukhrul", "Noney": "Noney", "Tengnoupal": "Tengnoupal", "Kamjong": "Kamjong",
    "Aizawl": "Aizawl", "Champhai": "Champhai", "Hnahthial": "Hnahthial", "Khawzawl": "Khawzawl",
    "Kolasib": "Kolasib", "Lawngtlai": "Lawngtlai", "Lunglei": "Lunglei", "Mamit": "Mamit",
    "Mammit": "Mamit", "Saiha": "Saiha", "Siaha": "Saiha", "Saitual": "Saitual", "Serchhip": "Serchhip",
    "East": "Gangtok", "East Sikkim": "Gangtok", "Gangtok": "Gangtok", "North": "Mangan",
    "North Sikkim": "Mangan", "Mangan": "Mangan", "South": "Namchi", "South Sikkim": "Namchi",
    "Namchi": "Namchi", "West": "Gyalshing", "West Sikkim": "Gyalshing", "Gyalshing": "Gyalshing",
    "Pakyong": "Pakyong", "Soreng": "Soreng",

    # --- PUDUCHERRY & ANDAMAN & DNHDD ---
    "Karaikal": "Karaikal", "Pondicherry": "Puducherry", "Puducherry": "Puducherry",
    "Yanam": "Yanam", "Mahe": "Mahe", "Andamans": "South Andaman", "Nicobar": "Nicobar",
    "Nicobars": "Nicobar", "North And Middle Andaman": "North and Middle Andaman",
    "North and Middle Andaman": "North and Middle Andaman", "South Andaman": "South Andaman",
    "South Andamans": "South Andaman", "Dadra & Nagar Haveli": "Dadra and Nagar Haveli",
    "Dadra And Nagar Haveli": "Dadra and Nagar Haveli", "Dadra and Nagar Haveli": "Dadra and Nagar Haveli",
    "Daman": "Daman", "Daman and Diu": "Daman", "Daman And Diu": "Daman", "Diu": "Diu",

    # --- GOA, CHANDIGARH & LAKSHADWEEP ---
    "North Goa": "North Goa", "South Goa": "South Goa", "Bardez": "North Goa",
    "Bicholim": "North Goa", "Tiswadi": "North Goa", "Panjim": "North Goa",
    "Madgaon": "South Goa", "Margao": "South Goa", "Chandigarh": "Chandigarh",
    "Lakshadweep": "Lakshadweep", "Laccadive": "Lakshadweep", "Kavaratti": "Lakshadweep",
    "Lakshadweep Islands": "Lakshadweep",

    # --- ANDHRA PRADESH ---
    "Alluri Sitharama Raju": "Alluri Sitharama Raju", "Anakapalli": "Anakapalli",
    "Anantapur": "Ananthapuramu", "Ananthapuramu": "Ananthapuramu", "Annamayya": "Annamayya",
    "Bapatla": "Bapatla", "Chittoor": "Chittoor", "Dr. B.R. Ambedkar Konaseema": "Dr. B.R. Ambedkar Konaseema",
    "East Godavari": "East Godavari", "Eluru": "Eluru", "Guntur": "Guntur", "Kakinada": "Kakinada",
    "Krishna": "Krishna", "Kurnool": "Kurnool", "Nandyal": "Nandyal", "NTR": "NTR",
    "N. T. R": "NTR", "Palnadu": "Palnadu", "Parvathipuram Manyam": "Parvathipuram Manyam",
    "Prakasam": "Prakasam", "Sri Potti Sriramulu Nellore": "Sri Potti Sriramulu Nellore",
    "Spsr Nellore": "Sri Potti Sriramulu Nellore", "Sri Sathya Sai": "Sri Sathya Sai",
    "Srikakulam": "Srikakulam", "Tirupati": "Tirupati", "Visakhapatnam": "Visakhapatnam",
    "Vizianagaram": "Vizianagaram", "West Godavari": "West Godavari",
    "Y.S.R. Kadapa": "Y.S.R. Kadapa", "Cuddapah": "Y.S.R. Kadapa",

    # --- BIHAR ---
    "Araria": "Araria", "Arwal": "Arwal", "Aurangabad": "Aurangabad", "Banka": "Banka",
    "Begusarai": "Begusarai", "Bhagalpur": "Bhagalpur", "Bhojpur": "Bhojpur", "Buxar": "Buxar",
    "Darbhanga": "Darbhanga", "East Champaran": "East Champaran", "Gaya": "Gaya",
    "Gopalganj": "Gopalganj", "Jamui": "Jamui", "Jehanabad": "Jehanabad", "Kaimur": "Kaimur",
    "Bhabua": "Kaimur", "Katihar": "Katihar", "Khagaria": "Khagaria", "Kishanganj": "Kishanganj",
    "Lakhisarai": "Lakhisarai", "Madhepura": "Madhepura", "Madhubani": "Madhubani",
    "Munger": "Munger", "Muzaffarpur": "Muzaffarpur", "Nalanda": "Nalanda", "Nawada": "Nawada",
    "Patna": "Patna", "Purnia": "Purnia", "Purnea": "Purnia", "Rohtas": "Rohtas",
    "Saharsa": "Saharsa", "Samastipur": "Samastipur", "Saran": "Saran", "Sheikhpura": "Sheikhpura",
    "Sheohar": "Sheohar", "Sitamarhi": "Sitamarhi", "Siwan": "Siwan", "Supaul": "Supaul",
    "Vaishali": "Vaishali", "West Champaran": "West Champaran",

    # --- TAMIL NADU & ODISHA ---
    "Ariyalur": "Ariyalur", "Chengalpattu": "Chengalpattu", "Chennai": "Chennai",
    "Coimbatore": "Coimbatore", "Cuddalore": "Cuddalore", "Dharmapuri": "Dharmapuri",
    "Dindigul": "Dindigul", "Erode": "Erode", "Kallakurichi": "Kallakurichi",
    "Kancheepuram": "Kancheepuram", "Kanchipuram": "Kancheepuram", "Kanniyakumari": "Kanniyakumari",
    "Kanyakumari": "Kanniyakumari", "Karur": "Karur", "Krishnagiri": "Krishnagiri",
    "Madurai": "Madurai", "Mayiladuthurai": "Mayiladuthurai", "Nagapattinam": "Nagapattinam",
    "Namakkal": "Namakkal", "Namakkal    *": "Namakkal", "Nilgiris": "Nilgiris",
    "Perambalur": "Perambalur", "Pudukkottai": "Pudukkottai", "Ramanathapuram": "Ramanathapuram",
    "Ranipet": "Ranipet", "Salem": "Salem", "Sivaganga": "Sivaganga", "Tenkasi": "Tenkasi",
    "Thanjavur": "Thanjavur", "Theni": "Theni", "Thoothukkudi": "Thoothukkudi",
    "Tuticorin": "Thoothukkudi", "Tiruchirappalli": "Tiruchirappalli", "Tirunelveli": "Tirunelveli",
    "Tirupathur": "Tirupattur", "Tiruppur": "Tiruppur", "Tiruvallur": "Tiruvallur",
    "Tiruvannamalai": "Tiruvannamalai", "Tiruvarur": "Tiruvarur", "Vellore": "Vellore",
    "Villupuram": "Villupuram", "Virudhunagar": "Virudhunagar", "Angul": "Angul",
    "Anugul": "Angul", "Balangir": "Balangir", "Baleswar": "Baleswar", "Baleshwar": "Baleswar",
    "Bargarh": "Bargarh", "Bhadrak": "Bhadrak", "Boudh": "Boudh", "Baudh": "Boudh",
    "Cuttack": "Cuttack", "Deogarh": "Deogarh", "Dhenkanal": "Dhenkanal", "Gajapati": "Gajapati",
    "Ganjam": "Ganjam", "Jagatsinghpur": "Jagatsinghpur", "Jajpur": "Jajpur", "Jajapur": "Jajpur",
    "Jajapur *": "Jajpur", "Jharsuguda": "Jharsuguda", "Kalahandi": "Kalahandi",
    "Kandhamal": "Kandhamal", "Kendrapara": "Kendrapara", "Kendrapara *": "Kendrapara",
    "Kendujhar": "Kendujhar", "Khordha": "Khordha", "Khorda": "Khordha", "Khordha *": "Khordha",
    "Koraput": "Koraput", "Malkangiri": "Malkangiri", "Mayurbhanj": "Mayurbhanj",
    "Nabarangpur": "Nabarangpur", "Nayagarh": "Nayagarh", "Nuapada": "Nuapada",
    "Puri": "Puri", "Rayagada": "Rayagada", "Sambalpur": "Sambalpur", "Subarnapur": "Subarnapur",
    "Sonapur": "Subarnapur", "Sundargarh": "Sundargarh"
}

# Replace values
df["district"] = df["district"].replace(district_map)

# Save output
df.to_csv("enrollment_new.csv", index=False)

print("District names updated successfully!")
